apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ .Chart.Name }}-config

data:
  SPRING_PROFILES_ACTIVE: {{ .Values.config.springProfile | quote }}
  MYSQL_DATABASE: {{ .Values.config.databaseName | quote }}