apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-db
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-db
    spec:
      containers:
          - name: mysql
            image: {{ .Values.database.image }}
            ports:
              - containerPort: {{ .Values.database.port }}
            env:
              - name: MYSQL_ROOT_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ .Chart.Name }}-secret
                    key: MYSQL_ROOT_PASSWORD
              - name: MYSQL_DATABASE
                valueFrom:
                  configMapKeyRef:
                    name: {{ .Chart.Name }}-config
                    key: MYSQL_DATABASE

              - name: MYSQL_USER
                valueFrom:
                  secretKeyRef:
                    name: {{ .Chart.Name }}-secret
                    key: REPLATE_DATASOURCE_USER

              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ .Chart.Name }}-secret
                    key: REPLATE_DATASOURCE_PASSWORD

            volumeMounts:
              - name: mysql-data
                mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-db-pvc