apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-db
spec:
  selector:
    app: {{ .Chart.Name }}-db
  ports:
      - name: mysql
        port: {{ .Values.database.port }}
        targetPort: {{ .Values.database.port }}
  type: ClusterIP