apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-db
spec:
  clusterIP: None
  selector:
    app: {{ .Chart.Name }}-db
  ports:
  - port: {{ .Values.database.port }}
    targetPort: {{ .Values.database.port }}