auth:
  image:
    repository: myacr.azurecr.io/replate-auth
    tag: latest
    pullPolicy: IfNotPresent

core:
  image:
    repository: myacr.azurecr.io/replate-core
    tag: latest
    pullPolicy: IfNotPresent

image:
  image:
    repository: myacr.azurecr.io/replate-image
    tag: latest
    pullPolicy: IfNotPresent