auth:
  image:
    repository: msoaacr.azurecr.io/test/replate-auth
    tag: latest
    pullPolicy: IfNotPresent

core:
  image:
    repository: msoaacr.azurecr.io/test/replate-core
    tag: latest
    pullPolicy: IfNotPresent

image:
  image:
    repository: msoaacr.azurecr.io/test/replate-image
    tag: latest
    pullPolicy: IfNotPresent